### ISSUE TITLE
The image is confusing

### ISSUE THREAD

**Issue by ElviraQDP** [4GeeksAcademy/javascript-dom-tutorial-exercises#20]
while the examples and exercises talk about ul and li, the picture says UL and  LI. While reading for the first time might me confusing
![README-es-md-—-javascript-dom-tutorial-exercises-—-Gitpod-Code](https://user-images.githubusercontent.com/63673743/124824054-dedea900-df3f-11eb-98f1-3f6b2a852021.png)

**Comment by ElviraQDP** [comment]
Then te exercise intruction talks about parentLI

**Comment by tommygonzaleza** [comment]
The instructions are clear, they actually look good
